Syncthing Improvements (#1378)
* DBC22-6710: Add DB Retention Interval to Syncthing

* DBC22-6712: Add retry to OpenShift login

* DBC22-6715: Add CPU Limit to Syncthing

* DBC22-6667: Update oauth-proxy to 4.18

diff --git a/.github/actions/oc-setup/action.yaml b/.github/actions/oc-setup/action.yaml
--- a/.github/actions/oc-setup/action.yaml
+++ b/.github/actions/oc-setup/action.yaml
@@ -31,10 +31,27 @@ runs:
 
     - name: Authenticate and set project
       shell: bash
-      env:
-        OC_SERVER: ${{ inputs.server }}
-        OC_TOKEN: ${{ inputs.token }}
-        OC_NAMESPACE: ${{ inputs.namespace }}
       run: |
-        oc login --server="$OC_SERVER" --token="$OC_TOKEN"
-        oc project "$OC_NAMESPACE"
+        attempt=1
+        max_attempts=3
+
+        until [ $attempt -gt $max_attempts ]
+        do
+          echo "Attempt $attempt of $max_attempts..."
+
+          if oc login --server=${{ inputs.server }} --token=${{ inputs.token }} \
+            && oc project ${{ inputs.namespace }}; then
+            echo "Login successful"
+            break
+          fi
+
+          if [ $attempt -eq $max_attempts ]; then
+            echo "All attempts failed"
+            exit 1
+          fi
+
+          echo "Login failed. Retrying in 30 seconds..."
+          sleep 30
+
+          attempt=$((attempt+1))
+        done
